info:
  title: Product API with Headers & Query Params
  version: 1.0.0
openapi: 3.0.0
paths:
  /products:
    get:
      parameters:
      - in: query
        name: category
        required: true
        schema:
          type: string
      - in: header
        name: X-Auth-Token
        required: true
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  message:
                    type: string
                  products:
                    items:
                      properties:
                        id:
                          type: string
                        name:
                          type: string
                        price:
                          type: number
                      type: object
                    type: array
                type: object
          description: Successful response
      summary: Get products by category
