openapi: 3.0.0
info:
  title: Product API
  version: 1.0.0
paths:
  /products:
    get:
      summary: Get products
      parameters:
      - name: category
        in: query
        required: false
        schema:
          type: string
          enum:
          - books
          - electronics
          - fashion
      - name: X-Auth-Token
        in: header
        required: true
        schema:
          type: string
      responses:
        '200':
          description: List of products
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Success
                  products:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          format: uuid
                          example: 5e63957c-4867-49a7-a81a-b3b91032598c
                        name:
                          type: string
                          example: David Hart DVM
                        price:
                          type: number
                          example: 934.09
