openapi: 3.0.0
info:
  title: Product Catalog API
  version: 1.0.0
paths:
  /products:
    get:
      summary: List all products
      parameters:
      - name: category
        in: query
        required: false
        schema:
          type: string
      - name: X-Auth-Token
        in: header
        required: true
        schema:
          type: string
      responses:
        '200':
          description: A list of products
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  products:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          format: uuid
                        name:
                          type: string
                        price:
                          type: number
